### ISSUE TITLE
[Question] Does the API TOKEN have an expiry?

### ISSUE THREAD

**Issue by bugbrekr** [anbuchelva/ev-log-bot#1]
Does the `API TOKEN` in the Ather app get refreshed after a period of time or is it permanently linked to a phone/installation?\
If it does expire after while, how would I know about it while using the API? just wait for errors or is there a known duration of lifespan for every token?

Thank you.

**Comment by anbuchelva** [comment]
AFAIK, the token gets expired on the following scenarios 
- when you log off from the app which you have acquired the token
- when Ather updates their app, mostly they forcefully logoff from all the devices 
- some random cases, reason not known 

I have used the same token for 3 months as well.

**Comment by bugbrekr** [comment]
> I have used the same token for 3 months as well.

That's reassuring.

Thanks for the insight.
